#!/usr/bin/env ansible-playbook
---

- name: Install backupninja
  hosts: g_backupninja

  tasks:

    - { name: Use augeas, import_role: { name: augeas }}

    - become: True
      block:

      - name: Install pkgs
        apt: { name: [ backupninja, augeas-tools, python-augeas, python3-augeas, python-yaml, python-paramiko ] }

      - name: Install augeas lens
        copy:
          content: |
            module PhpLike =
                autoload xfm
                let filter = incl "/etc/backupninja.conf"
                let xfm = transform Php.lns filter
          dest: /usr/share/augeas/lenses/phplike.aug

      - name: Config backupninja
        loop:
          - { option: reportinfo, value: 'yes' }
          - { option: reportspace, value: 'yes' }
        augeas:
          command: set
          path: /files/etc/backupninja.conf/.anon/{{ item.option }}
          value: '{{ item.value }}'
        when: False

      - name: Config backupninja using lininfile instead of augeas
        loop:
          - { option: reportinfo, value: 'yes' }
          - { option: reportspace, value: 'yes' }
        lineinfile:
          path: /etc/backupninja.conf
          regexp: ^{{ item.option }}
          line: '{{ item.option }} = {{ item.value }}'

      - { meta: noop, name: top }

      - vars:
          base: &base /usr/share/backupninja
          file: dup
          apath: &path '{{ base }}/{{ file}}'
          patch: &patch '{{ apath }}.patch'
        block:
        - name: Copy patch file
          copy:
            src: install-backupninja-dup.patch
            dest: '{{ patch }}'

        - stat: { path: *path }
          register: path
        - stat: { path: *patch }
          register: patch

        - name: Patch duplicity backend to allow password file inclusion
          when: path.stat.exists and patch.stat.exists
          patch:
            src: *patch
            basedir: *base
            remote_src: True
