#!/usr/bin/env ansible-playbook
---

- name: Install backupninja
  hosts: g_backupninja
  gather_facts: True

  tasks:

    - { name: Use augeas, import_role: { name: augeas }}

    - become: True
      block:

      - name: Install pkgs
        apt: { name: [ backupninja, augeas-tools, python-augeas, python-yaml, python-paramiko ] }
        when: ansible_distribution_release != "bullseye"

      - name: Install pkgs
        apt: { name: [ backupninja, augeas-tools, python3-augeas, python3-yaml, python3-paramiko ] }
        when: ansible_distribution_release == "bullseye"

      - name: Install augeas lens
        copy:
          content: |
            module PhpLike =
                autoload xfm
                let filter = incl "/etc/backupninja.conf"
                let xfm = transform Php.lns filter
          dest: /usr/share/augeas/lenses/phplike.aug

      - name: Config backupninja
        loop:
          - { option: reportinfo, value: 'yes' }
          - { option: reportspace, value: 'yes' }
        augeas:
          command: set
          path: /files/etc/backupninja.conf/.anon/{{ item.option }}
          value: '{{ item.value }}'
        when: False

      - name: Config backupninja using lininfile instead of augeas
        loop:
          - { option: reportinfo, value: 'yes' }
          - { option: reportspace, value: 'yes' }
        lineinfile:
          path: /etc/backupninja.conf
          regexp: ^{{ item.option }}
          line: '{{ item.option }} = {{ item.value }}'

      - { meta: noop, name: top }

      - set_fact:
          patch_file: |-
            {% if ansible_distribution_major_version | int < 10 %}
            install-backupninja-dup.patch
            {% elif ansible_distribution_major_version | int == 10 %}
            install-backupninja-dup-debian10.patch
            {%- else %}
            install-backupninja-dup-debian11.patch
            {%- endif %}
        when: False

      - vars:
          base: &base /usr/share/backupninja
          file: dup
          apath: &path '{{ base }}/{{ file}}'
          patch: &patch '{{ apath }}.patch'
        block:
        - name: Copy patch file
          copy:
            src: '{{ patch_file }}'
            dest: '{{ patch }}'

        - stat: { path: *path }
          register: path
        - stat: { path: *patch }
          register: patch

        - name: Patch duplicity backend to allow password file inclusion
          when: path.stat.exists and patch.stat.exists
          patch:
            src: *patch
            basedir: *base
            remote_src: True

        when: False

      - set_fact: { patch_files: [ install-backupninja-dup.patch ] }
        when: ansible_distribution_major_version | int < 10

      - vars:
          args:
            patches: [ 1, 2 ]
            prefix: install-backupninja-dup-debian{{ ansible_distribution_major_version }}-
            suffix: .patch
          jq: . as $i | .patches | map(tostring | $i.prefix + . + $i.suffix)
        set_fact: { patch_files: "{{ args | moreati.jq.jq(jq) }}" }
        when: ansible_distribution_major_version | int >= 10

      - vars:
          base: /usr/share/backupninja
          file: dup
        block:
        - name: Copy patch files
          copy:
            src: '{{ item }}'
            dest: '{{ base }}'
          loop: '{{ patch_files }}'

        - stat: { path: '{{ base }}/{{ file }}' }
          register: path
        - loop: '{{ patch_files }}'
          stat: { path: '{{ base }}/{{ item }}' }
          register: patches

        - name: Patch duplicity backend to allow password file inclusion and support newer version of duplicity
          when: path.stat.exists and patches.results | moreati.jq.jq('map(.stat.exists) | all')
          patch:
            src: '{{ base }}/{{ item }}'
            basedir: '{{ base }}'
            remote_src: True
          loop: '{{ patch_files }}'
